name: Update README.md (develop)
author: Bert Pluymers
description: Update links in README.md to point to appropriate version's images

inputs:
    github_token:
        required: true
        description: "Github token to be used to upload to push updated readme."
    fail_if_updated:
        required: false
        default: 'false'
        description: "Whether to fail the action if the README was updated (true/false)"

outputs:
    readme_updated:
        description: "Whether the README.md was actually updated and committed (true/false)"
        value: ${{ steps.update_readme.outputs.readme_updated }}

runs:
    using: "composite"
    steps:
      - name: Checkout code
        uses: actions/checkout@v5
        with:
          token: '${{ inputs.github_token }}'
          ref: ${{ github.ref }}   # check out the triggering ref

      - name: Determine Build Type
        id: build_type
        uses: ./.github/actions/build_type

      - uses: astral-sh/setup-uv@v7

      - name: Update README URLs & Commit changes
        id: update_readme
        shell: bash
        run: |
          git config --local user.name "GitHub Actions"
          git config --local user.email ""          
          git remote set-url origin https://x-access-token:${{ inputs.github_token }}@github.com/${{ github.repository }}.git          
          git pull origin "$GITHUB_REF"
          
          uv run --python 3.13 .github/scripts/update_readme_urls.py "$GITHUB_WORKSPACE/.python-versions" "$GITHUB_WORKSPACE/pyproject.toml" "$GITHUB_WORKSPACE/README.md" "${{ steps.build_type.outputs.build_type }}"
          echo "----------------------------------------------------------"
          cat "$GITHUB_WORKSPACE/README.md" | head -n 10
          echo "..."
          echo "----------------------------------------------------------"

          if git diff --quiet; then
              echo "readme_updated=false" >> $GITHUB_OUTPUT
              echo "No changes to commit"
          else
              git add "$GITHUB_WORKSPACE/README.md"
              git commit -m "Update README.md for ${{ steps.build_type.outputs.build_type }}/v$(uv version --short)"
              git push
              echo "readme_updated=true" >> $GITHUB_OUTPUT
              echo "Changes committed and pushed"
              
              if [ "${{ inputs.fail_if_updated }}" = "true" ]; then
                  echo "ERROR: README.md was updated & fail_if_updated is set to true."
                  exit 1
              fi
          fi
