name: Check ChangeLog
author: Bert Pluymers
description: Check if ChangeLog is part of PR & has version number in it


runs:
  using: "composite"
  steps:
      - name: Checkout code
        uses: actions/checkout@v5
        with:
          fetch-depth: 0

      - uses: astral-sh/setup-uv@v7

      - name: Check if Change Log was updated in PR
        if: github.event_name == 'pull_request'
        shell: bash
        run: |
          git fetch origin ${{  github.event.pull_request.base.ref  }}
          CHANGED_FILES=$(git diff --name-only origin/${{  github.event.pull_request.base.ref  }}...HEAD)
          if echo "$CHANGED_FILES" | grep -q "CHANGELOG.md"; then
            echo "CHANGELOG.md found in diff --> OK"
          else
            echo "CHANGELOG.md NOT found in diff --> FAIL"
            exit -1
          fi

      - name: Check if change log contains current version
        shell: bash
        run: |
          CURRENT_VERSION=$(uv version --short)
          if grep -q "$CURRENT_VERSION" CHANGELOG.md; then
            echo "CHANGELOG.md contains current version $CURRENT_VERSION --> OK"
          else
            echo "CHANGELOG.md does NOT contain current version $CURRENT_VERSION --> FAIL"
            exit -1
          fi