name: Update Splash Image
author: Bert Pluymers
description: Generate updated Splash image with appropriate package version.

inputs:
    uv_version:
        required: true
        description: "Version of UV to be used."
    github_token:
        required: true
        description: "Github token to be used to upload to github pages"


runs:
    using: "composite"
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          token: '${{ inputs.github_token }}'
          ref: develop  # this always acts upon the develop branch

      - name: Install uv
        uses: astral-sh/setup-uv@v7
        with:
          version: ${{ inputs.uv_version }}

      - name: Determine Package version
        shell: bash
        run: |
            PACKAGE_VERSION=$(uv version --short)
            echo "PACKAGE_EFFECTIVE_VERSION=$PACKAGE_VERSION" >> $GITHUB_ENV            

      - name: Install ImageMagick 7
        uses: mfinelli/setup-imagemagick@v7

      - name: Prepare splash screen
        shell: bash
        run: |
            magick -pointsize 96 -font "./images/splash/google_fonts_montserrat_bold.ttf" "./images/splash/splash.webp" -gravity South -fill "#aaaaaa" -annotate +0+50 "Collection of Python utilities for personal use." "./images/temp.png"
            magick -pointsize 36 -font "./images/splash/google_fonts_montserrat_italic.ttf" "./images/temp.png" -gravity SouthWest -fill "#aaaaaa" -annotate +10+5 "DiffusionBee 2.5.3 (FLUX.1-dev + Real-ESRGAN)" "./images/temp.png"
            magick -pointsize 128 -font "./images/splash/google_fonts_montserrat_bold.ttf" "./images/temp.png" -gravity West -fill "black" -annotate +1403+563 "v${PACKAGE_EFFECTIVE_VERSION}" "./images/temp.png"            
            magick -pointsize 128 -font "./images/splash/google_fonts_montserrat_bold.ttf" "./images/temp.png" -gravity West -fill "white" -annotate +1400+560 "v${PACKAGE_EFFECTIVE_VERSION}" -quality 99 -define webp:lossless=false "./images/splash_with_version.webp"                                                
            mkdir -p "./splash"
            cp "./images/splash_with_version.webp" "./splash/splash.webp"           

      - name: Pass splash to next action
        uses: actions/upload-artifact@v4
        with:
          name: splash
          path: ./splash/