name: Update Badge images based on Unit Test Coverage
author: Bert Pluymers
description: Generate unit test coverage & update badges.

inputs:
    github_token:
        required: true
        description: "Github token to be used to upload to github pages."


runs:
    using: "composite"
    steps:
      - name: Checkout code
        uses: actions/checkout@v5
        with:
          token: '${{ inputs.github_token }}'
          ref: ${{ github.ref }} # check out the triggering ref

      - uses: astral-sh/setup-uv@v7

      - name: Get Python versions
        id: python_versions
        uses: ./.github/actions/python_versions

      - name: Create coverage report
        shell: bash
        run: |
            uv venv
            source .venv/bin/activate
            uv sync
            uv run --python ${{ steps.python_versions.outputs.python_version_min }} pytest ./tests --junitxml=junit.xml --cov --cov-report=xml
            uv run --python ${{ steps.python_versions.outputs.python_version_max }} --all-extras pytest ./tests --junitxml=junit.xml --cov --cov-append --cov-report=xml

      - name: Generate badges
        shell: bash
        run: |            
            uv run genbadge tests -i junit.xml -o "./badges/badge-test-count.svg"
            uv run genbadge coverage -i coverage.xml -o "./badges/badge-coverage.svg"

      - name: Pass badges to next action
        uses: actions/upload-artifact@v4
        with:
          name: badges
          path: ./badges/
