name: Publish to dev
on:
  workflow_dispatch:


jobs:
  publish-to-dev:
    runs-on: ubuntu-latest
    environment: dev
    permissions:
      # IMPORTANT: this permission is mandatory for Trusted Publishing
      id-token: write
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install uv
        uses: astral-sh/setup-uv@v6
        with:
          version: ${{ vars.UV_VERSION }}

      - name: Update version in pyproject.toml
        shell: bash
        run: |
          ver_dev="$(uv version --short).dev${{ github.run_number }}"
          echo "Updating version to ${ver_dev}"
          uv version "${ver_dev}"

      - name: Build package with uv
        shell: bash
        run: uv build

      - name: Publish package distributions to PyPI   [---DEV---]
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          repository-url: https://test.pypi.org/legacy/

