name: Push to Develop
on:
  push:
    branches: ["develop"]

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
          python_version: ["3.11", "3.12", "3.13"]
          dependency_resolution: ["lowest-direct", "highest"]
          include_all_extra_deps: ["false", "true"]
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - uses: ./.github/actions/unit_test
        with:
          uv_version: ${{ vars.UV_VERSION }}
          python_version: ${{ matrix.python_version }}
          dependency_resolution: ${{ matrix.dependency_resolution }}
          include_all_extra_deps: ${{ matrix.include_all_extra_deps }}


  update-readme:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - uses: ./.github/actions/update_readme
        with:
          uv_version: ${{ vars.UV_VERSION }}
          github_token: ${{ secrets.GIT_ADMIN_TOKEN }}


  update-badges:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - uses: ./.github/actions/update_badges
        with:
          uv_version: ${{ vars.UV_VERSION }}
          github_token: ${{ secrets.GIT_ADMIN_TOKEN }}

  update-splash:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - uses: ./.github/actions/update_splash
        with:
          uv_version: ${{ vars.UV_VERSION }}
          github_token: ${{ secrets.GIT_ADMIN_TOKEN }}

  upload-version-artefacts:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: [update-badges, update-splash]
    permissions:
      contents: write
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - uses: ./.github/actions/upload_version_artefacts
        id: deployment
        with:
          uv_version: ${{ vars.UV_VERSION }}
          github_token: ${{ secrets.GIT_ADMIN_TOKEN }}